Repository FlightCoordinator/FlightCoordinator, pull requests merged in 2024-12, with the labels that each got.

#5 Authentication feature
  server/src/main/java/com/flightcoordinator/server/auth/CustomLogoutHandler.java
  server/src/main/java/com/flightcoordinator/server/controller/SystemRoleController.java
  server/src/main/java/com/flightcoordinator/server/controller/UserController.java
  server/src/main/java/com/flightcoordinator/server/dto/AuthDetailsDTO.java
  server/src/main/java/com/flightcoordinator/server/dto/LoginDetailsDTO.java
  server/src/main/java/com/flightcoordinator/server/dto/LoginResponseDTO.java
  server/src/main/java/com/flightcoordinator/server/dto/RegisterDetailsDTO.java
  server/src/main/java/com/flightcoordinator/server/entity/AirportEntity.java
  server/src/main/java/com/flightcoordinator/server/entity/AlgorithmResultEntity.java
  server/src/main/java/com/flightcoordinator/server/entity/AlgorithmRunEntity.java
  server/src/main/java/com/flightcoordinator/server/entity/CertificationEntity.java
  server/src/main/java/com/flightcoordinator/server/entity/CrewEntity.java
  server/src/main/java/com/flightcoordinator/server/entity/PlaneEntity.java
  server/src/main/java/com/flightcoordinator/server/entity/RouteEntity.java
  server/src/main/java/com/flightcoordinator/server/entity/UserEntity.java
  server/src/main/java/com/flightcoordinator/server/entity/VehicleEntity.java
  server/src/main/java/com/flightcoordinator/server/service/AlgorithmResultService.java
  server/src/main/java/com/flightcoordinator/server/service/AlgorithmRunService.java
  server/src/main/java/com/flightcoordinator/server/service/CertificationService.java
  server/src/main/java/com/flightcoordinator/server/service/CrewService.java
  server/src/main/java/com/flightcoordinator/server/service/PlaneService.java
  server/src/main/java/com/flightcoordinator/server/service/RouteService.java
  server/src/main/java/com/flightcoordinator/server/service/RunwayService.java
  server/src/main/java/com/flightcoordinator/server/service/SystemRoleService.java
  server/src/main/java/com/flightcoordinator/server/service/UserService.java
  server/src/main/java/com/flightcoordinator/server/service/VehicleService.java
  server/src/main/java/com/flightcoordinator/server/token/TokenRepository.java
  server/src/main/java/com/flightcoordinator/server/token/TokenService.java
Labels: enhancement

#12 made changes on entities
  server/pom.xml
  server/src/main/java/com/flightcoordinator/server/auth/CustomLogoutHandler.java
  server/src/main/java/com/flightcoordinator/server/auth/JWTAuthenticationFilter.java
  server/src/main/java/com/flightcoordinator/server/auth/SecurityConfig.java
  server/src/main/java/com/flightcoordinator/server/auth/token/TokenEntity.java
  server/src/main/java/com/flightcoordinator/server/entity/AirportEntity.java
  server/src/main/java/com/flightcoordinator/server/entity/AlgorithmResultEntity.java
  server/src/main/java/com/flightcoordinator/server/entity/AlgorithmRunEntity.java
  server/src/main/java/com/flightcoordinator/server/entity/CertificationEntity.java
  server/src/main/java/com/flightcoordinator/server/entity/CrewEntity.java
  server/src/main/java/com/flightcoordinator/server/entity/FlightEntity.java
  server/src/main/java/com/flightcoordinator/server/entity/PlaneEntity.java
  server/src/main/java/com/flightcoordinator/server/entity/RouteEntity.java
  server/src/main/java/com/flightcoordinator/server/entity/RunwayEntity.java
  server/src/main/java/com/flightcoordinator/server/entity/SystemRoleEntity.java
  server/src/main/java/com/flightcoordinator/server/entity/UserEntity.java
  server/src/main/java/com/flightcoordinator/server/entity/VehicleEntity.java
  server/src/main/resources/example.application.yml
  server/src/test/java/com/flightcoordinator/server/FlightCoordinatorBackendServerApplicationTests.java
Labels: bug, enhancement, java

#23 Created missing hooks for resources
  frontend/src/hooks/algorithmResult/useAlgorithmResultAllQuery.ts
  frontend/src/hooks/algorithmResult/useAlgorithmResultByIdQuery.ts
  frontend/src/hooks/algorithmResult/useAlgorithmResultDeleteMutation.ts
  frontend/src/hooks/algorithmRun/useAlgorithmDetailsQuery.ts
  frontend/src/hooks/algorithmRun/useAlgorithmRunAllQuery.ts
  frontend/src/hooks/algorithmRun/useAlgorithmRunByIdQuery.ts
  frontend/src/hooks/algorithmRun/useAlgorithmRunDeleteMutation.ts
  frontend/src/hooks/algorithmRun/useAlgorithmTriggerMutation.ts
  frontend/src/hooks/external/useFetchAirportsFromExternal.ts
  frontend/src/hooks/external/useFetchPlanesFromExternal.ts
  frontend/src/hooks/external/useFetchRoutesFromExternal.ts
  frontend/src/hooks/flight/useFlightAllQuery.ts
  frontend/src/hooks/flight/useFlightByIdQuery.ts
  frontend/src/hooks/flight/useFlightCreateMutation.ts
  frontend/src/hooks/flight/useFlightDeleteMutation.ts
  frontend/src/hooks/flight/useFlightUpdateMutation.ts
  frontend/src/hooks/useAccessToken.ts
Labels: enhancement

#24 updated hooks and changed queryparams
  frontend/src/hooks/airport/useAirportUpdateMutation.ts
  frontend/src/hooks/certification/useCertificationAllQuery.ts
  frontend/src/hooks/certification/useCertificationByIdQuery.ts
  frontend/src/hooks/certification/useCertificationCreateMutation.ts
  frontend/src/hooks/certification/useCertificationDeleteMutation.ts
  frontend/src/hooks/certification/useCertificationQuery.ts
  frontend/src/hooks/certification/useCertificationUpdateMutation.ts
  frontend/src/hooks/crew/useCrewAllQuery.ts
  frontend/src/hooks/crew/useCrewByIdQuery.ts
  frontend/src/hooks/crew/useCrewCreateMutation.ts
  frontend/src/hooks/crew/useCrewDeleteMutation.ts
  frontend/src/hooks/crew/useCrewQuery.ts
  frontend/src/hooks/crew/useCrewUpdateMutation.ts
  frontend/src/hooks/plane/usePlaneAllQuery.ts
  frontend/src/hooks/plane/usePlaneByIdQuery.ts
  frontend/src/hooks/plane/usePlaneCreateMutation.ts
  frontend/src/hooks/plane/usePlaneDeleteMutation.ts
  frontend/src/hooks/plane/usePlaneQuery.ts
  frontend/src/hooks/plane/usePlaneUpdateMutation.ts
  frontend/src/hooks/route/useRouteAllQuery.ts
  frontend/src/hooks/route/useRouteByIdQuery.ts
  frontend/src/hooks/route/useRouteCreateMutation.ts
  frontend/src/hooks/route/useRouteDeleteMutation.ts
  frontend/src/hooks/route/useRouteQuery.ts
  frontend/src/hooks/route/useRouteUpdateMutation.ts
  frontend/src/hooks/runway/useRunwayAllQuery.ts
  frontend/src/hooks/runway/useRunwayByIdQuery.ts
  frontend/src/hooks/runway/useRunwayCreateMutation.ts
  frontend/src/hooks/runway/useRunwayDeleteMutation.ts
  frontend/src/hooks/runway/useRunwayQuery.ts
  frontend/src/hooks/runway/useRunwayUpdateMutation.ts
  frontend/src/hooks/vehicle/useVehicleAllQuery.ts
  frontend/src/hooks/vehicle/useVehicleByIdQuery.ts
  frontend/src/hooks/vehicle/useVehicleCreateMutation.ts
  frontend/src/hooks/vehicle/useVehicleDeleteMutation.ts
  frontend/src/hooks/vehicle/useVehicleQuery.ts
  frontend/src/hooks/vehicle/useVehicleUpdateMutation.ts
  frontend/src/types/resource.d.ts
Labels: enhancement

#26 Backend devtools
  server/pom.xml
  server/src/main/java/com/flightcoordinator/server/auth/SecurityConfig.java
  server/src/main/java/com/flightcoordinator/server/controller/DevToolsController.java
  server/src/main/java/com/flightcoordinator/server/dev/SampleDataController.java
  server/src/main/java/com/flightcoordinator/server/devtools/SampleDataGenerator.java
  server/src/main/java/com/flightcoordinator/server/devtools/SampleDataValues.java
  server/src/main/java/com/flightcoordinator/server/dto/CertificationDTO.java
  server/src/main/java/com/flightcoordinator/server/dto/CrewDTO.java
  server/src/main/java/com/flightcoordinator/server/entity/CrewEntity.java
  server/src/main/java/com/flightcoordinator/server/service/CrewService.java
  server/src/main/java/com/flightcoordinator/server/service/DevToolsService.java
  server/src/main/java/com/flightcoordinator/server/utils/ObjectMapper.java
Labels: enhancement, java
